const CONFIG = {
  colors: {
    up: "#e74c3c",
    down: "#27ae60",
    accent: "#534ab7",
    accentLight: "#eeedfe",
    success: "#1d9e75",
    warning: "#ef9f27",
    info: "#378add",
    bgPrimary: "#ffffff",
    bgSecondary: "#f8f9fa",
    textPrimary: "#1a1a2e",
    textSecondary: "#6c757d",
    border: "#e0e0e0",
    series: ["#534ab7", "#1d9e75", "#ef9f27", "#378add", "#e74c3c", "#27ae60", "#d4537e", "#854f0b"],
  },
  stock: {
    name: "宁德时代",
    code: "300750.SZ",
    dataRange: "2025-07-04 ~ 2026-07-03",
    source: "Tushare Pro",
  },
  dataPath: "data/",
  imagePath: "images/",
  tasks: [
    {
      id: 1,
      title: "数据获取与可视化",
      subtitle: "TASK1 - 行情数据获取与股票走势展示",
      desc: "通过Tushare API获取宁德时代242个交易日日线数据，绘制收盘价走势曲线",
      tags: ["Python", "matplotlib", "Tushare"],
      img: "images/task1/ningde_close_price.png",
      pdf: "pdfs/夏阳+TASK1.pdf",
      charts: 1,
      metrics: [
        { val: "242", lbl: "交易日" },
        { val: "300750", lbl: "股票代码" },
      ],
    },
    {
      id: 2,
      title: "技术指标分析",
      subtitle: "TASK2 - RSI/MACD/布林带/KDJ",
      desc: "计算并可视化四大经典技术指标，含缺失值检查和描述性统计",
      tags: ["RSI", "MACD", "布林带", "KDJ"],
      img: "images/task2/chart_all_indicators.png",
      pdf: "pdfs/夏阳+TASK2.pdf",
      charts: 5,
      metrics: [
        { val: "4", lbl: "技术指标" },
        { val: "5", lbl: "可视化图表" },
      ],
    },
    {
      id: 3,
      title: "双均线策略回测",
      subtitle: "TASK3 - 金叉死叉信号与参数对比",
      desc: "双均线(MA)策略回测，3组参数(5/15,10/30,20/60)×4只股票对比验证",
      tags: ["双均线", "回测", "夏普比率", "多股票"],
      img: "images/task3/fig1_price_ma_signal.png",
      pdf: "pdfs/夏阳+TASK3.pdf",
      charts: 7,
      metrics: [
        { val: "+24.1%", lbl: "最优收益", up: true },
        { val: "0.76", lbl: "夏普比率" },
      ],
    },
    {
      id: 4,
      title: "海龟交易策略",
      subtitle: "TASK4 - 唐奇安通道+ATR止损",
      desc: "经典海龟交易策略回测，唐奇安通道突破+2倍ATR动态止损，含双系统进阶版",
      tags: ["海龟策略", "ATR", "止损纪律", "通道突破"],
      img: "images/task4/fig1_price_donchian_signal.png",
      pdf: "pdfs/夏阳+TASK4.pdf",
      charts: 7,
      metrics: [
        { val: "3组", lbl: "通道参数" },
        { val: "4只", lbl: "对比股票" },
      ],
    },
    {
      id: "4_advanced",
      title: "双系统海龟进阶",
      subtitle: "TASK4_advanced - 金字塔加仓+做空",
      desc: "经典双系统(S1=20/10, S2=55/20)海龟，含金字塔加仓、对称做空、ATR定仓",
      tags: ["双系统", "金字塔加仓", "做空", "ATR定仓"],
      img: "images/task4_advanced/fig1_dual_system_signal.png",
      pdf: "pdfs/Task4_plus.pdf",
      charts: 7,
      metrics: [
        { val: "2系统", lbl: "S1+S2" },
        { val: "4只", lbl: "对比股票" },
      ],
    },
    {
      id: 5,
      title: "ML分类实战",
      subtitle: "TASK5 - 逻辑回归/决策树/随机森林",
      desc: "三种分类算法应用于乳腺癌数据与股票收益数据，ROC/AUC/混淆矩阵评估",
      tags: ["分类模型", "ROC", "AUC", "混淆矩阵"],
      img: "images/task5/roc_stock.png",
      pdf: "pdfs/夏阳+TASK5.pdf",
      charts: 6,
      metrics: [
        { val: "3", lbl: "分类模型" },
        { val: "2", lbl: "数据集" },
      ],
    },
    {
      id: 6,
      title: "ML选股策略",
      subtitle: "TASK6 - 4分类+5回归模型",
      desc: "基于ML模型的选股交易策略，季度截面选股，含特征重要性和超额收益分析",
      tags: ["ML选股", "季度截面", "特征重要性", "超额收益"],
      img: "images/task6/cumulative_returns.png",
      pdf: "pdfs/夏阳+TASK6.pdf",
      charts: 10,
      metrics: [
        { val: "+26.0%", lbl: "梯度提升收益", up: true },
        { val: "3.41", lbl: "夏普比率" },
      ],
    },
    {
      id: 7,
      title: "策略寻优与实盘模拟",
      subtitle: "TASK7 - 样本内外分离+1296组寻优",
      desc: "双均线策略样本内参数寻优+样本外前向测试，含成本敏感性和VaR/CVaR风险指标",
      tags: ["参数寻优", "样本内外", "VaR/CVaR", "成本敏感性"],
      img: "images/task7/fig4_param_heatmap.png",
      pdf: "pdfs/夏阳+TASK7.pdf",
      charts: 8,
      metrics: [
        { val: "1296", lbl: "参数组合" },
        { val: "1.24", lbl: "最优夏普" },
      ],
    },
    {
      id: 8,
      title: "综合学习报告",
      subtitle: "TASK8 - 8条实战建议",
      desc: "30页PDF综合报告，含封面/目录/摘要/五章正文/附录8条建议，系统化总结全流程",
      tags: ["综合报告", "自动目录", "路演"],
      img: "images/task8/fig_summary_strategies.png",
      pdf: "pdfs/夏阳+TASK8.pdf",
      charts: 6,
      metrics: [
        { val: "30页", lbl: "PDF报告" },
        { val: "8条", lbl: "实战建议" },
      ],
    },
  ],
  skills: [
    "Python", "Pandas", "NumPy", "Matplotlib", "ECharts", "Scikit-learn",
    "Tushare Pro", "HTML/CSS/JS", "量化回测", "技术分析", "机器学习",
    "风险管理", "数据可视化", "策略寻优", "ReportLab", "Chart.js",
  ],
};
